//! Regression gate: `--precursor-cal off` (PR-A's default) must produce
//! the same PIN and TSV row-set as the committed golden, byte-equal after
//! sorting rows by SpecId.
//!
//! Why sorted comparison and not strict byte equality:
//! the rayon-based search pipeline has a known tie-breaking nondeterminism
//! that varies row ORDER across runs (see `.github/workflows/ci.yml:41-43`
//! and the skipped `match_spectra_output_invariant_across_thread_counts`
//! test). Sorted-row comparison catches real content drift (the gate's
//! purpose: detect any change in the off-path output) while tolerating
//! the orthogonal row-ordering noise.
//!
//! Goldens at `test-fixtures/parity/goldens/precursor_cal_off.{pin,tsv}`
//! were generated by this branch's binary on this fixture. To regenerate
//! after an intentional off-path change, run:
//!
//! ```text
//! cargo build --release -p cimas
//! ./target/release/cimas \
//!   --spectrum test-fixtures/test.mgf \
//!   --database test-fixtures/BSA.fasta \
//!   --output-pin test-fixtures/parity/goldens/precursor_cal_off.pin \
//!   --output-tsv test-fixtures/parity/goldens/precursor_cal_off.tsv
//! ```

use std::path::PathBuf;
use std::process::Command;

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR points at crates/cimas at test compile time.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("canonicalize workspace root")
}

fn read_sorted_rows(path: &PathBuf) -> (String, Vec<String>) {
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let text = String::from_utf8(bytes)
        .unwrap_or_else(|_| panic!("non-utf8 in {}", path.display()));
    let mut lines = text.lines();
    let header = lines
        .next()
        .unwrap_or_else(|| panic!("empty file: {}", path.display()))
        .to_string();
    let mut rows: Vec<String> = lines.map(|s| s.to_string()).collect();
    rows.sort();
    (header, rows)
}

#[test]
fn precursor_cal_off_pin_tsv_match_golden_after_sort() {
    let root = workspace_root();
    let binary = PathBuf::from(env!("CARGO_BIN_EXE_cimas"));
    let spectra = root.join("test-fixtures/test.mgf");
    let fasta = root.join("test-fixtures/BSA.fasta");
    assert!(spectra.exists(), "fixture missing: {}", spectra.display());
    assert!(fasta.exists(), "fixture missing: {}", fasta.display());

    let outdir = tempfile::tempdir().expect("tempdir");
    let actual_pin = outdir.path().join("actual.pin");
    let actual_tsv = outdir.path().join("actual.tsv");

    let status = Command::new(&binary)
        .arg("--spectrum").arg(&spectra)
        .arg("--database").arg(&fasta)
        .arg("--output-pin").arg(&actual_pin)
        .arg("--output-tsv").arg(&actual_tsv)
        // No --precursor-cal flag → default 'off'.
        .status()
        .expect("run cimas");
    assert!(status.success(), "cimas exited {status}");

    let golden_pin = root.join("test-fixtures/parity/goldens/precursor_cal_off.pin");
    let golden_tsv = root.join("test-fixtures/parity/goldens/precursor_cal_off.tsv");

    let (actual_pin_hdr, actual_pin_rows) = read_sorted_rows(&actual_pin);
    let (golden_pin_hdr, golden_pin_rows) = read_sorted_rows(&golden_pin);
    let (actual_tsv_hdr, actual_tsv_rows) = read_sorted_rows(&actual_tsv);
    let (golden_tsv_hdr, golden_tsv_rows) = read_sorted_rows(&golden_tsv);

    assert_eq!(actual_pin_hdr, golden_pin_hdr, "PIN header drift");
    assert_eq!(actual_tsv_hdr, golden_tsv_hdr, "TSV header drift");
    assert_eq!(
        actual_pin_rows.len(),
        golden_pin_rows.len(),
        "PIN row count drift: actual {} vs golden {}",
        actual_pin_rows.len(),
        golden_pin_rows.len(),
    );
    assert_eq!(
        actual_tsv_rows.len(),
        golden_tsv_rows.len(),
        "TSV row count drift: actual {} vs golden {}",
        actual_tsv_rows.len(),
        golden_tsv_rows.len(),
    );

    if actual_pin_rows != golden_pin_rows {
        for (i, (a, g)) in actual_pin_rows.iter().zip(golden_pin_rows.iter()).enumerate() {
            if a != g {
                panic!(
                    "PIN row mismatch at sorted index {i}:\n  actual: {a}\n  golden: {g}",
                );
            }
        }
    }
    if actual_tsv_rows != golden_tsv_rows {
        for (i, (a, g)) in actual_tsv_rows.iter().zip(golden_tsv_rows.iter()).enumerate() {
            if a != g {
                panic!(
                    "TSV row mismatch at sorted index {i}:\n  actual: {a}\n  golden: {g}",
                );
            }
        }
    }
}
